version: "3.9"
services:
  internal:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp_internal
    expose:
      - "3334"                       
    environment:
      - MCP_PORT=3334              
    networks:
      - mcplab
    restart: unless-stopped

  remote:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp_remote
    ports:
      - "3333:3333"                
    depends_on:
      - internal
    networks:
      - mcplab
    restart: unless-stopped

networks:
  mcplab:
    driver: bridge
